# Generated by Django 2.2 on 2020-02-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TclContractQty',
            fields=[
                ('cnt_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('cus_name_th', models.CharField(blank=True, max_length=120, null=True)),
                ('zone_en', models.CharField(blank=True, max_length=30, null=True)),
                ('cnt_sign_frm', models.CharField(blank=True, max_length=30, null=True)),
                ('cnt_sign_to', models.CharField(blank=True, max_length=30, null=True)),
                ('cus_add1_th', models.CharField(blank=True, max_length=150, null=True)),
                ('city_th', models.CharField(blank=True, max_length=30, null=True)),
                ('sd', models.DecimalField(blank=True, db_column='SD', decimal_places=0, max_digits=38, null=True)),
                ('sn', models.DecimalField(blank=True, db_column='SN', decimal_places=0, max_digits=38, null=True)),
                ('cqty', models.DecimalField(blank=True, db_column='CQTY', decimal_places=0, max_digits=4, null=True)),
                ('dly_sd', models.IntegerField(db_column='DLY_SD')),
                ('dly_sn', models.IntegerField(db_column='DLY_SN')),
                ('dly_std', models.IntegerField(db_column='DLY_STD')),
                ('dly_stn', models.IntegerField(db_column='DLY_STN')),
                ('dly_dof', models.IntegerField(db_column='DLY_DOF')),
                ('dly_date', models.CharField(db_column='Dly_Date', max_length=13)),
                ('upd_date', models.DateTimeField(db_column='UPD_Date')),
            ],
            options={
                'db_table': 'TCl_Contract_QTY',
                'ordering': ('cnt_id',),
                'managed': False,
            },
        ),
    ]
